language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "N61LMJDkwATpH3hkjtvI9a88vbjPqAaWS2Js5Bg7lvOwiwbIf8gQFVX/qH2PRIcYuH8QqD43qKgsrKGcAkQ0kks2jrhx1Eok9XjdWHaGQj5nQ/aZY+RHd8YKWaD/YCbHzqdmqdy9ITlwuImsf24vmHxJzqCAjgHO953XoKMJbINL3PEh0PxLREYyX9dpJfDkzC4VERftBcTA5N4zHB4iETC5waRH9yNy+kWxSFLsOTfRhnN0d/lIv0ESuOFDyrEVeQDobMzqYKztshz2XTr1phUN2YMsdB2bnVTtfwHXXRH10sCPdNGSMfwvLYbe41nxOl8cJWKgtcYWDbAGlyJt6vqGN0dohVtKzNsfFJPr8SzbIbuY/5IrcwGu3kInz4tU2IAU/PNLIXzdH02pJiOs37r9S3TUVLuBUArR85PDq/DA4Vwz16EgXaEkR3c5/znYptVp67LxEwotPbAlTU8C9glcXs5lu8Abtdo1msk55NPMhDWCtRBFx81mxgPHOQLbfmS4hfC1CDQyntCSazASI+kDpzK249HIKTSSNkTKvKj8ls2F4WHqy0yu6Vvsbw1VXRC8btrh97rqnn2VfaZ1zbizDaZ1vIt3OdpKkHQuhmBtsNrm7fpRHhF+A3tFqT1r9shlgvC36T3RaYDWisooKrY582yiXq8T91HuAjVbeuk="
env:
  secure: "AVHYpM/Js+1tLnLFEbYIFdGUetvJXV8galAkRTyVpvWBGGpUucdftzMGX0/8p5a5Ohq+ZkJ6OXakL51HhKp9pVdzrLkfvZi3C7VysZ3LkJFQ+Zm2Br4/gayA5bmUfyBA19RiGW1dNQ5ri1Kyziqkhok+uh2GowNbEM69FKd7TMSXqfoUe8omzEYR+nR2TiwJ+FG/WJsmyP7vkWWYaZ6UHS0w3+t7MNfqJUNRzADRp1GCHJ3Ii0glUZ6u7pomfgMBhrBEpUADOtxFVdqPJq9hVsQ0lM1qGEqsLcpaZH3XHUcEp+1qbKPPm9A9L24lmEVrC7vQ8nW0piFvWaJXYAW91WjOzmfzegJFk0HclDbt/IZvI5vV6JUZiRDYWe4sVHu2H+Mj27K3a9njPIb6Jd9Vy5N9NWaAONmiEr/ckmXLW5c5HQySbvQlw6f7DNZ6I8vNNewajNnPUmYqSjqatXE67beP47HQvL35WXD6xQzApsIv/j4/5LLCEw+cRRIwg65fhKZF86nRMCGbDJeXbtsmlHMQS7fofgQMdwyNMEPFrMfxDgqDISsf3lCXJ1xlZw75j+U1Fte33lz0BYrSd4A9S7pumhd840wUN6e9tQ1A/JRGgR/Nqh2PL0ZpsJWN0wFJKirvJx1NGipdt4Sl/TBKNCpVJBL6Z7tVmvMMuezcKCo="
