language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "AVHYpM/Js+1tLnLFEbYIFdGUetvJXV8galAkRTyVpvWBGGpUucdftzMGX0/8p5a5Ohq+ZkJ6OXakL51HhKp9pVdzrLkfvZi3C7VysZ3LkJFQ+Zm2Br4/gayA5bmUfyBA19RiGW1dNQ5ri1Kyziqkhok+uh2GowNbEM69FKd7TMSXqfoUe8omzEYR+nR2TiwJ+FG/WJsmyP7vkWWYaZ6UHS0w3+t7MNfqJUNRzADRp1GCHJ3Ii0glUZ6u7pomfgMBhrBEpUADOtxFVdqPJq9hVsQ0lM1qGEqsLcpaZH3XHUcEp+1qbKPPm9A9L24lmEVrC7vQ8nW0piFvWaJXYAW91WjOzmfzegJFk0HclDbt/IZvI5vV6JUZiRDYWe4sVHu2H+Mj27K3a9njPIb6Jd9Vy5N9NWaAONmiEr/ckmXLW5c5HQySbvQlw6f7DNZ6I8vNNewajNnPUmYqSjqatXE67beP47HQvL35WXD6xQzApsIv/j4/5LLCEw+cRRIwg65fhKZF86nRMCGbDJeXbtsmlHMQS7fofgQMdwyNMEPFrMfxDgqDISsf3lCXJ1xlZw75j+U1Fte33lz0BYrSd4A9S7pumhd840wUN6e9tQ1A/JRGgR/Nqh2PL0ZpsJWN0wFJKirvJx1NGipdt4Sl/TBKNCpVJBL6Z7tVmvMMuezcKCo="
