language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "N61LMJDkwATpH3hkjtvI9a88vbjPqAaWS2Js5Bg7lvOwiwbIf8gQFVX/qH2PRIcYuH8QqD43qKgsrKGcAkQ0kks2jrhx1Eok9XjdWHaGQj5nQ/aZY+RHd8YKWaD/YCbHzqdmqdy9ITlwuImsf24vmHxJzqCAjgHO953XoKMJbINL3PEh0PxLREYyX9dpJfDkzC4VERftBcTA5N4zHB4iETC5waRH9yNy+kWxSFLsOTfRhnN0d/lIv0ESuOFDyrEVeQDobMzqYKztshz2XTr1phUN2YMsdB2bnVTtfwHXXRH10sCPdNGSMfwvLYbe41nxOl8cJWKgtcYWDbAGlyJt6vqGN0dohVtKzNsfFJPr8SzbIbuY/5IrcwGu3kInz4tU2IAU/PNLIXzdH02pJiOs37r9S3TUVLuBUArR85PDq/DA4Vwz16EgXaEkR3c5/znYptVp67LxEwotPbAlTU8C9glcXs5lu8Abtdo1msk55NPMhDWCtRBFx81mxgPHOQLbfmS4hfC1CDQyntCSazASI+kDpzK249HIKTSSNkTKvKj8ls2F4WHqy0yu6Vvsbw1VXRC8btrh97rqnn2VfaZ1zbizDaZ1vIt3OdpKkHQuhmBtsNrm7fpRHhF+A3tFqT1r9shlgvC36T3RaYDWisooKrY582yiXq8T91HuAjVbeuk="
